services:
  - type: web
    name: artiexperts-portfolio
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: NEXT_PUBLIC_SANITY_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_SANITY_DATASET
        sync: false
      - key: NEXT_PUBLIC_SANITY_API_VERSION
        value: "2025-11-16"
